### ISSUE TITLE
Using as auto-complete instead of snippet?

### ISSUE THREAD

**Issue by rangka-kacang** [dons20/UIKit-VSCode#15]
I'd like to be able to use all the class names as auto-complete instead of writing the whole html element.

For example:

Typing uk-sec will give an auto-complete suggestion for uk-section and when I press enter, it will only write uk-section instead of `<div class="uk-section"></div>`

This is very useful for fast reference. Instead of going back to the documentation to find something you need for example: uk-text-center uk-margin-small-right...

I hope you understand what I mean. I wrote a request and tag you on Uikit gitter but no reply so I'm opening a new issue. This will be a great feature. To know more how it works as I wanted, you can try the uikit plugin/extension for Sublime Text 3.

Thank you for your work. I appreciate it.

**Comment by dons20** [comment]
Hey @rangka-kacang, I replied via Gitter a few days ago because I didn't realize I was tagged there. There's a fairly simple workaround for getting this to work. 

You'll need to enable tab completion via "editor.tabCompletion": true or enable constant IntelliSense for strings, like so:

```json
"editor.quickSuggestions": {
    "comments": false,
    "other": true,
    "strings": true
}
```

Also for each snippet I usually include a base version which only outputs the class or attribute name. 
Once the intellisense will trigger inside strings, you can use them freely.

Let me know if this resolves the issue.

**Comment by rangka-kacang** [comment]
Thank you for your feedback @dons20 

It works fine for HTML files. However, I'm actually working on Laravel. It seems that the auto-complete did not trigger on *.blade.php files. How can I solve this?

**Comment by dons20** [comment]
That is because snippets have to be pre-defined to work with specific languages, however, I am looking into making it work globally. I'll investigate and see if this could be done to work in any file. Aside from that, I can always add any other extensions that are needed by users.

**Comment by dons20** [comment]
Ok, so after some investigation, and testing, I found that global snippets are an option and the next release will have UIKit snippets as global by default. I should have a release available within 24 hours.

**Comment by dons20** [comment]
Enabled in version 1.4.0 (44083be1fe9bee49f869889fa76f937d72dda8ec). Check the marketplace for the latest release and read the changelog for more details. Hope this helps!

I'll close the issue, but feel free to re-open if you have additional queries on this issue.
