### ISSUE TITLE
CDN Link not the latest version in VS Code Snippet

### ISSUE THREAD

**Issue by Marlice** [dons20/UIKit-VSCode#19]
- [x ] Check that you are running the latest version of Visual Studio Code
- [x ] Check that you are running the latest version of the snippet plugin (UIkit 3.0 Snippets 1.4.0)
- [x ] Check that the extension is enabled
- [x ] Check that your editor suggestions are enabled (or manually trigger them with <kbd>Ctrl</kbd> + <kbd>Space</kbd>

### Problem Encountered
The Snippet in VS Code "uk-$" with CDN-Link is 3.0.3.

should be updated to the latest Version
### Steps to Reproduce

1. UIkit documentation: https://getuikit.com/docs/installation
2. UIkit is 3.1.6

**Comment by dons20** [comment]
Hi, thanks for opening the issue. I just haven't gotten around to updating it to the latest release yet. I'll be updating it very soon though. I'm looking into automating those version updates.

**Comment by dons20** [comment]
Updated in latest release https://github.com/dons20/UIKit-VSCode/commit/48e7bfce9b3795ab8b95acada5981ac094834bbc
