### ISSUE TITLE
New version Not working

### ISSUE THREAD

**Issue by Uranbold** [dons20/UIKit-VSCode#2]
Is this not working on new version? Did you guys tried it?

**Comment by dons20** [comment]
Is what not working, the extension/snippets?

**Comment by Uranbold** [comment]
Yeah snippet seems not working.

**Comment by dons20** [comment]
Are you using the latest version?
Also it only works in `.html` and `.php` files.

**Comment by Uranbold** [comment]
Yeah Visual Studio has updated to new version to 1.11.1

**Comment by dons20** [comment]
It's currently working for me in Visual Studio Code 1.11.1. Have you tried using Alt+Enter to manually trigger suggestions?
Maybe you have auto-suggestions off in your editor?
Press F1 -> User Settings -> Look for "editor.quicksuggestions" -> Set "other": true
Also, check if there are any other settings that you might be using that stops it from working.

**Comment by Uranbold** [comment]
Ooh sorry for that. It seems working. But i have another extension for Autocompletting Class names and that's actually not working...

Thanks for fast response.

**Comment by dons20** [comment]
Glad to be of help, hope you manage to get that other extension working!
