### ISSUE TITLE
How Hide snipets in othes evironments ?

### ISSUE THREAD

**Issue by UpsylonDev** [dons20/UIKit-VSCode#20]
Hello ! 
Thanx for your great tool ! ;-) 

but :
How Hide snipets in others evironments ? 
i'm in VSCODE. there are everywhere now :'(
;-)

**Comment by dons20** [comment]
Hi, thanks for using the extension!

The easiest way to have the snippets hidden in other environments is to disable the plugin globally, and then enable it in the workspace you specifically want it enabled in.

So for clarity: **Disable UIKit-VSCode globally ➡ Enable it in the workspace you want**

Please check this page to see how it's done: https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension

Let me know if you have any further questions.
