### ISSUE TITLE
Not working with twig/PHP

### ISSUE THREAD

**Issue by ladislavsulc** [dons20/UIKit-VSCode#4]
Hi,

I am trying to make this work with twig/PHP templates for Wordpress development but so far no luck. Am I doing something wrong or is it working just for HTML?

Thank you.

**Comment by dons20** [comment]
Hi, 
The snippets work for html, php and javascript (js only snippets where applicable).

1. What problems are you encountering when you try to make it work?
2. Are you using a .html/.php/.js file?
3. Have you tried to manually trigger suggestions (Alt+Enter)?
4. Maybe your auto-suggestions are off as well? (Press F1 -> User Settings -> Look for "editor.quicksuggestions" -> Set "other": true)

**Comment by ladislavsulc** [comment]
Hi,

thank you for the reply. HTML, PHP now seems fine. I would love to use this with [Twig files](https://twig.sensiolabs.org/) Would it be possible to add this functionality, perhaps in the future?

Thank you.

**Comment by dons20** [comment]
Sure, that's definitely possible. I can enable it to work with any type of files I choose, so twig files are definitely an option.

What file extensions are used for twig? I'm not very familiar with it myself.

**Comment by ladislavsulc** [comment]
Thank you!
It is .twig (all documented here [https://twig.sensiolabs.org/](url).

As for extensions - [https://marketplace.visualstudio.com/items?itemName=whatwedo.twig](url).

Hope it helps.

**Comment by dons20** [comment]
I've enabled .twig support in my local files, and it will be enabled in the extension in the next release (v1.1.1). Should be sometime this week, so you can look out for it.
